# Generated by Django 6.0.3 on 2026-03-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(default='#ff9ec8', max_length=20)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
            ],
        ),
    ]
