# Generated by Django 6.0.3 on 2026-03-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='bg_color',
            field=models.CharField(default='#be185d', max_length=20),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
