# Generated by Django 6.0.3 on 2026-03-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_alter_themesetting_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('npm', models.CharField(max_length=20, unique=True)),
                ('jurusan', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(help_text='Format: YYYY-MM-DD')),
                ('hobi', models.CharField(max_length=255)),
                ('quotes', models.TextField()),
                ('avatar', models.ImageField(blank=True, help_text='Upload gambar profil', null=True, upload_to='avatars/')),
            ],
        ),
    ]
