# Generated by Django 6.0.3 on 2026-03-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_profilmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='font_family',
            field=models.CharField(default='Roboto, sans-serif', max_length=100),
        ),
    ]
