# Generated by Django 6.0.3 on 2026-04-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0004_themesetting_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_backgrounds/'),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='theme_mode',
            field=models.CharField(default='original', max_length=20),
        ),
    ]
